### ISSUE TITLE
New-AsBuiltReport : A parameter cannot be found that matches parameter name 'Token'.

### ISSUE THREAD

**Issue by euanmatthews** [AsBuiltReport/AsBuiltReport.Rubrik.CDM#21]
Error when trying to run the initial report in the Readme.md 

New-AsBuiltReport -Target 'cluster1.domain.local' -Token '1234abcd' -Report Rubrik.CDM -Format Html,Word -OutputFolderPath 'C:\Reports' -Timestamp

![image](https://user-images.githubusercontent.com/48801309/191232891-350d59c2-6e5c-4d26-a821-d0a4fd13a31a.png)

**Comment by blckpythn** [comment]
Getting the same error when trying to use a token.
Checked the Invoke-AsBuiltReport.Rubrik.CDM.ps1 in the module and it does not have a Token parameter in the param block, it does however have a StylePath parameter, I believe the version here on Github and the version in the PSGallery are different.

I tried to replace what I had with the version in Github and then I got "New-AsBuiltReport : A parameter cannot be found that matches parameter name 'StylePath'." - believe both parameters will need to be present.

**Comment by blckpythn** [comment]
Can confirm, simply modifying the local copy of the Invoke-AsBuiltReport.Rubrik.CDM.ps1 file to make sure all parameters are available fixed it.
```    [cmdletbinding()]
    param (
        [String[]] $Target,
        [PSCredential] $Credential,
        [String] $Token,
	[String] $StylePath
    )

**Comment by tpcarman** [comment]
Nice find. Not sure how that has happened but you're right, the `master` branch is missing the `Token` parameter.

I will correct this and publish a new version to the PowerShell Gallery in the coming days. 

Note, the `StylePath` parameter is now redundant and should not be required.
