### ISSUE TITLE
Retrieving protected objects with no present filesets causes error

### ISSUE THREAD

**Issue by mwpreston** [AsBuiltReport/AsBuiltReport.Rubrik.CDM#6]
When processing the protected objects, the module mostly does null checks around everything.  This check isn't applied to filesets - therefore, it causes the report to error out due to the following error

```
Cannot validate argument on parameter 'id'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
```

Need to apply the same logic to filesets as all other protected objects.

**Comment by GideonSwheeler** [comment]
I found the error to be in the function Get-RubrikFileset the result is now a hash table so is never null
